name: CI

on:
  pull_request:
    branches: ["dev", "test"]
    types: [opened, synchronize, reopened, closed]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    # Checkout the repo
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    
    # Build and examine Go source code
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...

  golangci:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          # TODO: add yml config
          args: --timeout=5m -v
 
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push images to private repository
      - name: Build and push inventory-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: inventory-bmc-app
          tags: dev
          registry: ${{ env.REGISTRY }}
          githubOrg: ${{ github.actor }}
          dockerfile: Dockerfile.inventory
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push discovery-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: discovery-bmc-app
          tags: dev
          registry: ${{ env.REGISTRY }}
          githubOrg: ${{ github.actor }}
          dockerfile: Dockerfile.discovery
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push monitor-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: monitor-bmc-app
          tags: dev
          registry: ${{ env.REGISTRY }}
          githubOrg: ${{ github.actor }}
          dockerfile: Dockerfile.monitor
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push led-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: led-bmc-app
          tags: dev
          registry: ${{ env.REGISTRY }}
          githubOrg: ${{ github.actor }}
          dockerfile: Dockerfile.led
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
