name: CI

on:
  pull_request:
    branches: ["dev"]
    types: [opened, synchronize, reopened, closed]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    # Checkout the repo
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    
    # Build and examine Go source code
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...

  golangci:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          # TODO: add yml config
          args: --timeout=5m -v
 
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: imagename
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}

      - name: Build and push inventory-bmc-app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase }}/inventory-bmc-app:dev
          file: Dockerfile.inventory

      - name: Build and push discovery-bmc-app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase }}/discovery-bmc-app:dev
          file: Dockerfile.discovery

      - name: Build and push monitor-bmc-app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase }}/monitor-bmc-app:dev
          file: Dockerfile.monitor

      - name: Build and push led-bmc-app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase }}/led-bmc-app:dev
          file: Dockerfile.led
