name: CI

on:
  pull_request:
    branches: ["dev"]
    types: [closed]

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push inventory-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: inventory-bmc-app
          tags: dev
          dockerfile: Dockerfile.inventory

      - name: Build and push discovery-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: discovery-bmc-app
          tags: dev
          dockerfile: Dockerfile.discovery

      - name: Build and push monitor-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: monitor-bmc-app
          tags: dev
          dockerfile: Dockerfile.monitor

      - name: Build and push led-bmc-app
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: led-bmc-app
          tags: dev
          dockerfile: Dockerfile.led
